#!/system/bin/sh

# Super Battery-Performance ratio
# If MSM Hotplug is available the settings below will be set.

if [ -e "/sys/module/msm_hotplug/" ] && \
    [ ! -f "/data/xos/disable.auto.msm_hotplug" ]; then
    cd /sys/module/msm_hotplug/

    # Turn on
    echo -n '1'>msm_enabled

    # LITTLE
    echo 4 > max_cpus_online
    echo 2 > min_cpus_online
    echo 8 > offline_load
    # big
    echo 4 > max_cpus_online_big
    echo 1 > min_cpus_online_big
    echo 60 > online_load_big
    echo 18 > offline_load_big
    echo 0 > big_core_up_delay

    # Turn on all cores on this load
    echo 82 > fast_lane_load

    # When bigs should kick in
    echo 68 > kick_in_load_big

    # Display off
    echo 2 > max_cpus_online_susp

    echo 1 > io_is_busy

    cd
fi

exit 0
